name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Jalankan setiap hari tengah malam UTC
  workflow_dispatch:      # Dapat dijalankan manual lewat tab "Actions"
  push:
    branches:
      - main              # Jalankan saat ada push ke main

permissions:
  contents: write         # Diperlukan agar bot bisa push ke repo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      # 2. Generate the snake game SVG
      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 3. Push the generated snake to the output branch
      - name: Push Snake to output branch
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: output
          force: true

      # 4. (Opsional) Deploy hasilnya ke GitHub Pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
